### PR TITLE
upgrade to SIMDe 0.7.0

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by danoon2** [comment]
I modified SIMDe to make it more correct, so unfortunately it's not a simple thing to update the library.  If you are curious, you can see simde_mm_cvtss_si32 in sse.h.  I marked my changes with :TODO: .  In that function my change was to add

if (a.f32[0] >= 2147483648.0f || a.f32[0] <= -2147483649.0f) { // :TODO: I modified this
        return 0x80000000;
    } else {
        return (int32_t)a.f32[0];
    }

SSE states that with an overflow this function should return 0x80000000 and not just truncate, which is what SIMDe does.  I think in most cases what SIMDe does is fine, but for an emulator, I try to make all the instructions work as much as possible as the hardware.

**Comment by mr-c** [comment]
Yeah, I saw those modifications. I [added test cases based upon them](https://github.com/simd-everywhere/simde/pull/685) and now we see the same problems you faced, thanks!

I've also [opened an issue to remind us to add more overflow testing](https://github.com/simd-everywhere/simde/issues/688).

@nemequ is working on some fixes, which I can then add here. Or we can add your fixes back here as well. Which do you prefer?

**Comment by danoon2** [comment]
If SIMDe handles the overflow cases I will definitely update the library to use it.  I would prefer not to track my own changes to a library.  I wasn't sure that SIMDe would be interested in overflow cases like this because the hardware for ARM and x86 return different values.  I have this comment in my code for ARMv8,

When converting Double/Float to int32, if the value doesn't fit, SSE converts the value to 0x80000000, but ARM converts it to 0x7FFFFFFF

If it helps, here is the list of functions I had to modify because of under/overflow

simde_mm_cvtps_pi32
simde_mm_cvtss_si32
simde_mm_cvtt_ps2pi
simde_mm_cvttss_si32
simde_mm_cvtpd_epi32
simde_mm_cvtpd_pi32
simde_mm_cvtps_epi32
simde_mm_cvtsd_si32
simde_mm_cvttpd_epi32
simde_mm_cvttpd_pi32
simde_mm_cvttps_epi32
simde_mm_cvttsd_si32

**Comment by nemequ** [comment]
> If SIMDe handles the overflow cases I will definitely update the library to use it. 

I'm working on updating SIMDe now, I'll let you know when I'm done.

I'm also adding tests for handling NaN, which aren't right in your version either, so you should definitely sync your copy when I'm done.

>  I wasn't sure that SIMDe would be interested in overflow cases like this

We are. I'm adding a macro you can define to avoid the extra complexity for people who would prefer that, but it will be off by default (unless you build with `-ffast-math` or similar), but by default we should be correct for most things… slightly different answers from computation is generally okay (e.g., if the rsqrt approximations are a bit different, or an fma degrades to a multiply and an add, etc.) but the semantics should match.

> If it helps, here is the list of functions I had to modify because of under/overflow

It does, thanks! :)

**Comment by nemequ** [comment]
There will probably be more coming soon, but as of [c3d7abfaba6729a8b11d09a314b34a4db628911d](https://github.com/simd-everywhere/simde/commit/c3d7abfaba6729a8b11d09a314b34a4db628911d) all the functions on your list should be done.

**Comment by mr-c** [comment]
@danoon2 I've updated this PR to include the fix that @nemequ mentioned along with adding `-DSIMDE_NO_FAST_CONVERSION_RANGE` to the build scripts. 

I haven't done any testing, so I guess that is up to you :-)

**Comment by mr-c** [comment]
@danoon2 pardon me, we now default to **not** setting `SIMDE_FAST_CONVERSION_RANGE` when `SIMDE_FAST_MATH` is not set, so there is no need for manually setting `SIMDE_NO_FAST_CONVERSION_RANGE`.

Note that passing `-ffast-math` will cause `SIMDE_FAST_MATH` to be set and therefore `SIMDE_FAST_CONVERSION_RANGE` to be active,

**Comment by danoon2** [comment]
@mr-c I was able to get things to build.  I didn't need a min/max test for it before, so I'm not sure why that changed, but on the Raspberry pi simde_mm_cvt_ss2si fails unless I do the same check that was added to simde_mm_cvtt_ss2si, it was return int max instead of int min.

My unit tests are certainly not complete for all edge cases, but I feel like I got a lot of them.  With the small fix to simde_mm_cvt_ss2si, the new SIMDe code passes on x86 for Mac, Windows and Linux and on the Raspberry Pi ARMv7 and on Emscripten.  For my use case I had to turn on the following defines

#define SIMDE_NO_NATIVE
#define SIMDE_NO_VECTOR
#define SIMDE_NO_CHECK_IMMEDIATE_CONSTANT

**Comment by mr-c** [comment]
@danoon2 thanks for catching that oversight! I've got a fix and I'll add it to this PR.

**Comment by danoon2** [comment]
Ok, I merged in the changes into master.    Currently I'm only tracking 1 set of changes to the library to make it work in my project.  I commented out the <windows.h> include and commented out the MemoryBarrior call which needed windows.h.   My project doesn't handle windows.h being included in the part of the code that uses sse.h.  Maybe someday I will make that work.

**Pull request closed without merging**
